# Generated by Django 5.0.4 on 2024-04-05 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resident_uid', models.UUIDField()),
                ('problem_description', models.TextField()),
                ('society', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Society.society')),
            ],
        ),
    ]
