# Generated by Django 5.0.4 on 2024-04-05 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0003_problem'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Problem',
        ),
    ]
