# Generated by Django 5.0.4 on 2024-04-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0004_delete_problem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='residentproblem',
            name='resident_uid',
        ),
    ]
