# Generated by Django 5.0.4 on 2024-04-05 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0005_remove_residentproblem_resident_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentproblem',
            name='society',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_problems', to='Society.society'),
        ),
    ]
