# Generated by Django 5.0.4 on 2024-04-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0006_alter_residentproblem_society'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentproblem',
            name='solved',
            field=models.BooleanField(default=False),
        ),
    ]
