# Generated by Django 5.0.4 on 2024-04-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0008_alter_residentproblem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentproblem',
            name='room_number',
            field=models.CharField(default='Unknown', max_length=10),
        ),
    ]
