# Generated by Django 5.0.4 on 2024-04-05 20:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0009_residentproblem_room_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='residentproblem',
            name='room_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
