# Generated by Django 5.0.4 on 2024-04-05 21:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Society', '0010_alter_residentproblem_room_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='residentproblem',
            name='phone_number',
            field=models.CharField(default=1, max_length=20, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
    ]
